# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20180225_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=20)),
                ('assignment_file', models.FileField(upload_to='teacher_assignment')),
                ('share', models.BooleanField(default=False)),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_name', models.CharField(max_length=20)),
                ('slide_file', models.FileField(upload_to='teacher_slide')),
                ('share', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='assignment',
            field=models.ManyToManyField(to='teacher.Assignment'),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='slide',
            field=models.ManyToManyField(to='teacher.Slides'),
        ),
    ]
