# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20180225_1849'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slides',
            new_name='Slide',
        ),
    ]
