# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 16:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20180227_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
