# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_auto_20180228_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachermodel',
            old_name='username',
            new_name='user',
        ),
    ]
