# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20180225_0434'),
        ('teacher', '0008_auto_20180228_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachermodel',
            name='course',
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Course'),
        ),
    ]
